name: "Build and Push"

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - "master"

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    outputs:
      image_id: ${{ steps.image_id.outputs.image_id }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - id: image_id
        name: Generate Image ID
        run: |
          echo "::set-output name=image_id::${{ env.REGISTRY }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.image_id.outputs.image_id }}
          
